services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMq__Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitMq__Password}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    env_file:
      - .env

  signalr-hub:
    image: signalrhub
    build:
      context: ./ServerMonitoringSystem.SignalRHub
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "8080:80"
    env_file:
      - .env

  server-monitoring-system-collector:
    image: server-monitoring-system-collector
    build:
      context: ./ServerMonitoringSystem.Collector
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ServerStatisticsSettings__SamplingIntervalSeconds=${ServerStatisticsSettings__SamplingIntervalSeconds}
      - ServerStatisticsSettings__ServerIdentifier=${ServerStatisticsSettings__ServerIdentifier}
      - RabbitMq__Hostname=${RabbitMq__Hostname}
      - RabbitMq__Username=${RabbitMq__Username}
      - RabbitMq__Password=${RabbitMq__Password}
    env_file:
      - .env

  server-monitoring-system-analyzer:
    image: server-monitoring-system-analyzer
    build:
      context: ./ServerMonitoringSystem.Analyzer
      dockerfile: Dockerfile
    depends_on:
      - server-monitoring-system-collector
      - mongodb
      - signalr-hub
    environment:
      - RabbitMq__Hostname=${RabbitMq__Hostname}
      - RabbitMq__Username=${RabbitMq__Username}
      - RabbitMq__Password=${RabbitMq__Password}
      - MongoDbSettings__ConnectionString=${MongoDbSettings__ConnectionString}
      - SignalRSettings__SignalRUrl=${SignalRSettings__SignalRUrl}
    env_file:
      - .env