services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMq__Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitMq__Password}
    env_file:
      - .env

  server-monitoring-system:
    image: server-monitoring-system
    build:
      context: ./ServerMonitoringSystem
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ServerStatisticsSettings__SamplingIntervalSeconds=${ServerStatisticsSettings__SamplingIntervalSeconds}
      - ServerStatisticsSettings__ServerIdentifier=${ServerStatisticsSettings__ServerIdentifier}
      - RabbitMq__Hostname=${RabbitMq__Hostname}
      - RabbitMq__Username=${RabbitMq__Username}
      - RabbitMq__Password=${RabbitMq__Password}
    env_file:
      - .env